import paths from "@/paths"
import NoteDataType from "@/types/NoteDataType"
import Link from "next/link"

// This should be ultimately autogenerated from supabase

type NoteCardProps = {
  slug: string
  data: NoteDataType
}

const NoteCard = ({ slug, data }: NoteCardProps) => {
  const { id, title } = data
  return (
    <div>
      <Link href={paths.showNote(slug, id)}>{title}</Link>
    </div>
  )
}

export default NoteCard
