import paths from "@/paths"
import Link from "next/link"

// This should be ultimately autogenerated from supabase

type NoteDataType = {
  id: number
  title: string
  content: string
  user_id: number
  notebook_id: number
  created_at: number
  updated_at: number
}

type NoteListProps = {
  slug: string
  data: NoteDataType
}

const NoteCard = ({ slug, data }: NoteListProps) => {
  const { id, title } = data
  return (
    <div>
      <Link href={paths.showNote(slug, id)}>{title}</Link>
    </div>
  )
}

export default NoteCard
