import paths from "@/paths"
import Link from "next/link"

// This should be ultimately autogenerated from supabase

type NotebookDataType = {
  id: number
  title: string
  user_id: number
  created_at: number
  updated_at: number
}

type NotebooksListProps = {
  data: NotebookDataType
}

const NotebooksListCard = ({ data }: NotebooksListProps) => {
  const { title } = data
  return (
    <div>
      <Link href={paths.showNotebook(title)}>{title}</Link>
    </div>
  )
}

export default NotebooksListCard
